"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";

const PLAN_COLORS = { free:"text-white/30 bg-white/5", basico:"text-blue-400 bg-blue-500/10", premium:"text-yellow-400 bg-yellow-500/10", avancado:"text-purple-400 bg-purple-500/10" };
const cx=(...a)=>a.filter(Boolean).join(" ");

export default function AdminUsers() {
  const [users,setUsers]=useState([]), [total,setTotal]=useState(0), [page,setPage]=useState(1), [search,setSearch]=useState(""), [planFilter,setPlanFilter]=useState("all"), [loading,setLoading]=useState(true), [quickCredits,setQuickCredits]=useState(100), [msg,setMsg]=useState(null);
  const load=async()=>{setLoading(true);const params=new URLSearchParams({page,limit:20,search,plan:planFilter});const r=await fetch(`/api/admin/users?${params}`);const d=await r.json().catch(()=>({}));setUsers(d.users||[]);setTotal(d.total||0);setLoading(false)};
  useEffect(()=>{load()},[page,planFilter]); useEffect(()=>{const t=setTimeout(()=>{setPage(1);load()},400);return()=>clearTimeout(t)},[search]);
  const stats=useMemo(()=>({ credits: users.reduce((a,u)=>a+(u.credits||0),0), paid: users.filter(u=>u.plan&&u.plan!=="free").length, admins: users.filter(u=>u.role==="admin").length }),[users]);
  const addCredits=async(u)=>{const r=await fetch(`/api/admin/users/${u.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({addCredits:+quickCredits})});setMsg(r.ok?`+${quickCredits} créditos para ${u.email}`:"Erro ao adicionar créditos");load();setTimeout(()=>setMsg(null),2500)};
  const changePlan=async(u,plan)=>{await fetch(`/api/admin/users/${u.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({plan})});load()};
  return <div>
    <div className="mb-6 flex items-end justify-between gap-4"><div><h1 className="text-2xl font-bold text-white mb-1">User Management</h1><p className="text-sm text-white/40">Gerencie usuários, planos, créditos e acesso administrativo.</p></div><Link href="/admin/credits" className="px-3 py-2 rounded-lg text-xs font-semibold bg-yellow-500 text-black">Controle de créditos</Link></div>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-5"><Stat label="Usuários" value={total}/><Stat label="Pagantes nesta lista" value={stats.paid}/><Stat label="Créditos nesta lista" value={stats.credits}/><Stat label="Admins" value={stats.admins}/></div>
    {msg&&<div className="mb-4 text-xs text-yellow-400 bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-3">{msg}</div>}
    <div className="flex gap-3 mb-5 flex-wrap items-center"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by name or email…" className="bg-[#161616] border border-white/10 rounded-lg px-3 py-2 text-sm text-white placeholder-white/25 outline-none focus:border-white/25 w-64" />{["all","free","basico","premium","avancado"].map(p=><button key={p} onClick={()=>{setPlanFilter(p);setPage(1)}} className={cx("px-3 py-1.5 rounded-lg text-xs font-medium capitalize transition-colors",planFilter===p?"bg-yellow-500 text-black":"bg-white/5 text-white/50 hover:text-white")}>{p==="all"?"All Plans":p}</button>)}<div className="ml-auto flex items-center gap-2"><span className="text-xs text-white/35">Crédito rápido</span><input type="number" value={quickCredits} onChange={e=>setQuickCredits(e.target.value)} className="w-20 bg-[#161616] border border-white/10 rounded-lg px-2 py-1.5 text-xs text-white"/></div></div>
    <div className="bg-[#161616] border border-white/10 rounded-xl overflow-hidden"><table className="w-full text-sm"><thead><tr className="border-b border-white/10">{["User","Plan","Credits","Usage","Role","Joined","Quick Actions"].map(h=><th key={h} className="text-left px-4 py-3 text-xs font-medium text-white/30 uppercase tracking-wider">{h}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={7} className="text-center py-10 text-white/20 text-xs">Loading…</td></tr>:users.map(u=><tr key={u.id} className="border-b border-white/5 hover:bg-white/[.02] transition-colors"><td className="px-4 py-3"><div className="font-medium text-white/80 text-xs">{u.name||"—"}</div><div className="text-[11px] text-white/35">{u.email}</div></td><td className="px-4 py-3"><span className={cx("px-2 py-0.5 rounded text-[10px] font-semibold uppercase",PLAN_COLORS[u.plan]||PLAN_COLORS.free)}>{u.plan}</span></td><td className="px-4 py-3"><span className="text-yellow-400 font-medium text-xs">{u.credits} cr</span></td><td className="px-4 py-3 text-[11px] text-white/35">{u._count?.creations||0} criações · {u._count?.payments||0} pagamentos</td><td className="px-4 py-3"><span className={cx("text-[10px]",u.role==="admin"?"text-red-400":"text-white/30")}>{u.role||"user"}</span></td><td className="px-4 py-3 text-[11px] text-white/30">{new Date(u.createdAt).toLocaleDateString("pt-BR")}</td><td className="px-4 py-3"><div className="flex gap-2 flex-wrap"><button onClick={()=>addCredits(u)} className="text-[11px] px-2 py-1 bg-yellow-500 text-black rounded font-semibold">+{quickCredits}</button><select onChange={e=>changePlan(u,e.target.value)} value={u.plan||"free"} className="bg-black/30 border border-white/10 rounded px-2 py-1 text-[11px] text-white/60">{["free","basico","premium","avancado"].map(p=><option key={p}>{p}</option>)}</select><Link href={`/admin/users/${u.id}`} className="text-[11px] px-3 py-1 border border-white/15 rounded hover:border-white/30 text-white/60 hover:text-white transition-colors">Edit</Link></div></td></tr>)}{!loading&&users.length===0&&<tr><td colSpan={7} className="text-center py-10 text-white/20 text-xs">No users found</td></tr>}</tbody></table>{total>20&&<div className="flex items-center justify-between px-4 py-3 border-t border-white/10"><span className="text-xs text-white/30">Showing {(page-1)*20+1}–{Math.min(page*20,total)} of {total}</span><div className="flex gap-2"><button onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1} className="px-3 py-1 text-xs border border-white/10 rounded disabled:opacity-30 hover:border-white/25">← Prev</button><button onClick={()=>setPage(p=>p+1)} disabled={page*20>=total} className="px-3 py-1 text-xs border border-white/10 rounded disabled:opacity-30 hover:border-white/25">Next →</button></div></div>}</div>
  </div> }
function Stat({label,value}){return <div className="bg-[#161616] border border-white/10 rounded-xl p-4"><div className="text-xs text-white/35 mb-1">{label}</div><div className="text-xl font-bold text-white">{value}</div></div>}
