"use client";
import { useEffect, useState } from "react";

const PLAN_NAMES = { free: "Free", basico: "Básico", premium: "Premium", avancado: "Avançado" };
const cx = (...a) => a.filter(Boolean).join(" ");
function Card({ children, className="" }) { return <div className={cx("bg-[#161616] border border-white/10 rounded-xl p-5", className)}>{children}</div>; }
function Label({ children }) { return <label className="text-[11px] uppercase tracking-[.12em] text-white/35 block mb-1.5">{children}</label>; }
function Input(props) { return <input {...props} className={cx("w-full bg-[#101010] border border-white/10 rounded-lg px-3 py-2 text-sm text-white outline-none focus:border-yellow-500/60 placeholder-white/20", props.className)} />; }
function Select(props) { return <select {...props} className={cx("w-full bg-[#101010] border border-white/10 rounded-lg px-3 py-2 text-sm text-white outline-none focus:border-yellow-500/60", props.className)} />; }
function Textarea(props) { return <textarea {...props} className={cx("w-full bg-[#101010] border border-white/10 rounded-lg px-3 py-2 text-sm text-white outline-none focus:border-yellow-500/60 placeholder-white/20", props.className)} />; }
function Button({ children, className="", ...props }) { return <button {...props} className={cx("px-3 py-2 rounded-lg text-xs font-semibold transition-colors disabled:opacity-40", className || "bg-yellow-500 text-black hover:bg-yellow-400")} >{children}</button>; }
function Status({ on, label }) { return <span className={cx("text-[10px] px-2 py-1 rounded-full font-semibold", on ? "bg-green-500/10 text-green-400" : "bg-white/5 text-white/30")}>{label || (on ? "ON" : "OFF")}</span>; }

const ENV_LABELS = {
  DATABASE_URL:"Banco Neon", NEXTAUTH_URL:"URL pública do app", NEXTAUTH_SECRET:"Segredo NextAuth", GOOGLE_CLIENT_ID:"Google OAuth Client ID", GOOGLE_CLIENT_SECRET:"Google OAuth Secret", STRIPE_SECRET_KEY:"Stripe Secret Key", STRIPE_WEBHOOK_SECRET:"Stripe Webhook Secret", NEXT_PUBLIC_STRIPE_LINK_BASICO:"Stripe Link Básico", NEXT_PUBLIC_STRIPE_LINK_PREMIUM:"Stripe Link Premium", NEXT_PUBLIC_STRIPE_LINK_AVANCADO:"Stripe Link Avançado", MERCADOPAGO_ACCESS_TOKEN:"MercadoPago Access Token", BYTEPLUS_API_KEY:"BytePlus / Seedance", ATLASCLOUD_API_KEY:"Atlas Cloud"
};
export default function AdminSettings(){ const [data,setData]=useState(null); const [msg,setMsg]=useState(null); useEffect(()=>{fetch('/api/admin/platform').then(r=>r.ok?r.json():null).then(setData).catch(()=>setData({envChecklist:{}}));},[]); const origin=typeof window!=='undefined'?window.location.origin:'https://hollywoodstudio.ai'; const copy=(t)=>{navigator.clipboard.writeText(t);setMsg('Copiado');setTimeout(()=>setMsg(null),1500)};
  return <div><div className="mb-6"><h1 className="text-2xl font-bold text-white mb-1">Launch Settings</h1><p className="text-sm text-white/40">Checklist operacional: secrets ficam na Vercel; conteúdos comerciais ficam no Admin.</p></div>{msg&&<div className="mb-4 text-xs text-yellow-400">✓ {msg}</div>}<div className="grid grid-cols-1 lg:grid-cols-2 gap-5"><Card><h2 className="text-sm font-semibold mb-1">Environment Variables</h2><p className="text-xs text-white/35 mb-4">Configure em Vercel → Project → Environment Variables.</p><div className="space-y-2">{Object.entries(ENV_LABELS).map(([k,label])=><div key={k} className="flex items-center justify-between gap-3 border-b border-white/5 pb-2"><div><div className="text-xs text-white/70 font-mono">{k}</div><div className="text-[11px] text-white/30">{label}</div></div><Status on={!!data?.envChecklist?.[k]} label={data?.envChecklist?.[k]?'OK':'Falta'}/></div>)}</div></Card><Card><h2 className="text-sm font-semibold mb-1">Webhook URLs</h2><p className="text-xs text-white/35 mb-4">Copie para Stripe, MercadoPago e BytePlus/Atlas.</p>{[{p:'Stripe',u:`${origin}/api/stripe/webhook`,e:'checkout.session.completed'},{p:'MercadoPago',u:`${origin}/api/mercadopago/webhook`,e:'payment'},{p:'BytePlus/AI',u:`${origin}/api/webhook/byteplus`,e:'generation callback'},{p:'NextAuth Google',u:`${origin}/api/auth/callback/google`,e:'Authorized redirect URI'}].map(w=><div key={w.p} className="bg-[#101010] border border-white/5 rounded-lg p-3 mb-3"><div className="flex justify-between text-xs mb-2"><b>{w.p}</b><span className="text-white/35">{w.e}</span></div><div className="flex gap-2"><code className="text-[11px] text-yellow-400 truncate flex-1">{w.u}</code><button onClick={()=>copy(w.u)} className="text-[10px] px-2 py-1 border border-white/10 rounded text-white/50">Copy</button></div></div>)}</Card></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-5"><Card><h3 className="font-semibold text-white">Planos</h3><p className="text-xs text-white/35 mt-1 mb-3">Preços, links e créditos.</p><a className="text-xs text-yellow-400" href="/admin/plans">Abrir Plans →</a></Card><Card><h3 className="font-semibold text-white">Modelos</h3><p className="text-xs text-white/35 mt-1 mb-3">Ativar Atlas, Seedance e providers.</p><a className="text-xs text-yellow-400" href="/admin/models">Abrir Models →</a></Card><Card><h3 className="font-semibold text-white">Branding</h3><p className="text-xs text-white/35 mt-1 mb-3">Logo, idioma, tema e suporte.</p><a className="text-xs text-yellow-400" href="/admin/branding">Abrir Branding →</a></Card></div></div> }
