"use client";
import { useEffect, useMemo, useState } from "react";

const PLAN_NAMES = { free: "Free", basico: "Básico", premium: "Premium", avancado: "Avançado" };
const cx = (...a) => a.filter(Boolean).join(" ");
function Card({ children, className="" }) { return <div className={cx("bg-[#161616] border border-white/10 rounded-xl p-5", className)}>{children}</div>; }
function Label({ children }) { return <label className="text-[11px] uppercase tracking-[.12em] text-white/35 block mb-1.5">{children}</label>; }
function Input(props) { return <input {...props} className={cx("w-full bg-[#101010] border border-white/10 rounded-lg px-3 py-2 text-sm text-white outline-none focus:border-yellow-500/60 placeholder-white/20", props.className)} />; }
function Select(props) { return <select {...props} className={cx("w-full bg-[#101010] border border-white/10 rounded-lg px-3 py-2 text-sm text-white outline-none focus:border-yellow-500/60", props.className)} />; }
function Textarea(props) { return <textarea {...props} className={cx("w-full bg-[#101010] border border-white/10 rounded-lg px-3 py-2 text-sm text-white outline-none focus:border-yellow-500/60 placeholder-white/20", props.className)} />; }
function Button({ children, className="", ...props }) { return <button {...props} className={cx("px-3 py-2 rounded-lg text-xs font-semibold transition-colors disabled:opacity-40", className || "bg-yellow-500 text-black hover:bg-yellow-400")} >{children}</button>; }
function Status({ on, label }) { return <span className={cx("text-[10px] px-2 py-1 rounded-full font-semibold", on ? "bg-green-500/10 text-green-400" : "bg-white/5 text-white/30")}>{label || (on ? "ON" : "OFF")}</span>; }

export default function AdminCredits(){ const [users,setUsers]=useState([]); const [search,setSearch]=useState(''); const [amount,setAmount]=useState(100); const [msg,setMsg]=useState(null); const [loading,setLoading]=useState(true);
  const load=async()=>{setLoading(true);const r=await fetch('/api/admin/users?limit=100&search='+encodeURIComponent(search)+'&plan=all');const d=await r.json().catch(()=>({}));setUsers(d.users||[]);setLoading(false)};
  useEffect(()=>{const t=setTimeout(load,300);return()=>clearTimeout(t)},[search]);
  const total=useMemo(()=>users.reduce((a,u)=>a+(u.credits||0),0),[users]);
  const add=async(u)=>{const r=await fetch('/api/admin/users/'+u.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({addCredits:+amount})});setMsg(r.ok?`+${amount} créditos adicionados para ${u.email}`:'Erro ao adicionar créditos');load()};
  return <div><div className="mb-6"><h1 className="text-2xl font-bold text-white mb-1">Credit Control</h1><p className="text-sm text-white/40">Libere créditos manualmente, acompanhe saldos e opere pagamentos assistidos.</p></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-5"><Card><div className="text-xs text-white/40">Usuários listados</div><div className="text-2xl font-bold text-white mt-1">{users.length}</div></Card><Card><div className="text-xs text-white/40">Saldo total listado</div><div className="text-2xl font-bold text-yellow-400 mt-1">{total} cr</div></Card><Card><div className="text-xs text-white/40">Crédito rápido</div><Input type="number" value={amount} onChange={e=>setAmount(e.target.value)} className="mt-2"/></Card></div>{msg&&<div className="mb-4 text-xs text-yellow-400 bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-3">{msg}</div>}<div className="mb-4"><Input placeholder="Buscar usuário por nome/email" value={search} onChange={e=>setSearch(e.target.value)} /></div><div className="bg-[#161616] border border-white/10 rounded-xl overflow-hidden"><table className="w-full text-sm"><thead><tr className="border-b border-white/10">{['Usuário','Plano','Créditos','Criações','Pagamentos','Ação'].map(h=><th key={h} className="text-left px-4 py-3 text-xs font-medium text-white/30 uppercase tracking-wider">{h}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={6} className="py-10 text-center text-white/25">Carregando…</td></tr>:users.map(u=><tr key={u.id} className="border-b border-white/5"><td className="px-4 py-3"><div className="text-xs text-white/80">{u.name||'—'}</div><div className="text-[11px] text-white/35">{u.email}</div></td><td className="px-4 py-3 text-xs capitalize text-white/50">{u.plan}</td><td className="px-4 py-3 text-yellow-400 font-semibold text-xs">{u.credits} cr</td><td className="px-4 py-3 text-xs text-white/40">{u._count?.creations||0}</td><td className="px-4 py-3 text-xs text-white/40">{u._count?.payments||0}</td><td className="px-4 py-3"><Button onClick={()=>add(u)}>+{amount} cr</Button></td></tr>)}</tbody></table></div></div> }
