"use client";
import { useEffect, useState } from "react";

const PLAN_NAMES = { free: "Free", basico: "Básico", premium: "Premium", avancado: "Avançado" };
const cx = (...a) => a.filter(Boolean).join(" ");
function Card({ children, className="" }) { return <div className={cx("bg-[#161616] border border-white/10 rounded-xl p-5", className)}>{children}</div>; }
function Label({ children }) { return <label className="text-[11px] uppercase tracking-[.12em] text-white/35 block mb-1.5">{children}</label>; }
function Input(props) { return <input {...props} className={cx("w-full bg-[#101010] border border-white/10 rounded-lg px-3 py-2 text-sm text-white outline-none focus:border-yellow-500/60 placeholder-white/20", props.className)} />; }
function Select(props) { return <select {...props} className={cx("w-full bg-[#101010] border border-white/10 rounded-lg px-3 py-2 text-sm text-white outline-none focus:border-yellow-500/60", props.className)} />; }
function Textarea(props) { return <textarea {...props} className={cx("w-full bg-[#101010] border border-white/10 rounded-lg px-3 py-2 text-sm text-white outline-none focus:border-yellow-500/60 placeholder-white/20", props.className)} />; }
function Button({ children, className="", ...props }) { return <button {...props} className={cx("px-3 py-2 rounded-lg text-xs font-semibold transition-colors disabled:opacity-40", className || "bg-yellow-500 text-black hover:bg-yellow-400")} >{children}</button>; }
function Status({ on, label }) { return <span className={cx("text-[10px] px-2 py-1 rounded-full font-semibold", on ? "bg-green-500/10 text-green-400" : "bg-white/5 text-white/30")}>{label || (on ? "ON" : "OFF")}</span>; }

const DEFAULT_FEATURES = { studio:true, gallery:true, directorAgent:true, finalCut:true, modelsCatalog:true, imglyEditor:false, academy:false, opportunities:false, marketplace:false, council:false };
const LABELS = { studio:"Studio", gallery:"Galeria", directorAgent:"Director Agent", finalCut:"Final Cut AI", modelsCatalog:"Catálogo de Modelos", imglyEditor:"IMG.LY Studio Editor", academy:"Academy", opportunities:"Opportunities", marketplace:"Marketplace", council:"Director's Council" };
export default function AdminFeatures(){ const [features,setFeatures]=useState(DEFAULT_FEATURES); const [msg,setMsg]=useState(null); const [saving,setSaving]=useState(false);
  useEffect(()=>{fetch('/api/admin/platform').then(r=>r.ok?r.json():null).then(d=>d?.features&&setFeatures(d.features)).catch(()=>{});},[]);
  const save=async()=>{setSaving(true);const r=await fetch('/api/admin/platform',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({features})});const d=await r.json().catch(()=>({}));setMsg(r.ok?'Features salvas':(d.error||'Erro ao salvar'));setSaving(false)};
  return <div><div className="mb-6 flex items-end justify-between"><div><h1 className="text-2xl font-bold text-white mb-1">Feature Flags</h1><p className="text-sm text-white/40">Controle o que aparece agora e o que fica como futuro/coming soon.</p></div><Button onClick={save} disabled={saving}>{saving?'Salvando…':'Salvar features'}</Button></div>{msg&&<div className="mb-4 text-xs text-yellow-400 bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-3">{msg}</div>}<div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">{Object.entries(features).map(([k,v])=><Card key={k}><div className="flex justify-between items-start gap-4"><div><h2 className="font-semibold text-white">{LABELS[k]||k}</h2><p className="text-xs text-white/35 mt-1">{v?'Disponível para usuários conforme plano.':'Oculto ou marcado como futuro.'}</p></div><button onClick={()=>setFeatures(f=>({...f,[k]:!f[k]}))} className={cx('w-12 h-7 rounded-full border transition-colors relative',v?'bg-yellow-500 border-yellow-500':'bg-white/5 border-white/10')}><span className={cx('absolute top-1 w-5 h-5 rounded-full bg-white transition-all',v?'left-6':'left-1')}/></button></div></Card>)}</div></div> }
