"use client";
import { useEffect, useState } from "react";

const PLAN_NAMES = { free: "Free", basico: "Básico", premium: "Premium", avancado: "Avançado" };
const cx = (...a) => a.filter(Boolean).join(" ");
function Card({ children, className="" }) { return <div className={cx("bg-[#161616] border border-white/10 rounded-xl p-5", className)}>{children}</div>; }
function Label({ children }) { return <label className="text-[11px] uppercase tracking-[.12em] text-white/35 block mb-1.5">{children}</label>; }
function Input(props) { return <input {...props} className={cx("w-full bg-[#101010] border border-white/10 rounded-lg px-3 py-2 text-sm text-white outline-none focus:border-yellow-500/60 placeholder-white/20", props.className)} />; }
function Select(props) { return <select {...props} className={cx("w-full bg-[#101010] border border-white/10 rounded-lg px-3 py-2 text-sm text-white outline-none focus:border-yellow-500/60", props.className)} />; }
function Textarea(props) { return <textarea {...props} className={cx("w-full bg-[#101010] border border-white/10 rounded-lg px-3 py-2 text-sm text-white outline-none focus:border-yellow-500/60 placeholder-white/20", props.className)} />; }
function Button({ children, className="", ...props }) { return <button {...props} className={cx("px-3 py-2 rounded-lg text-xs font-semibold transition-colors disabled:opacity-40", className || "bg-yellow-500 text-black hover:bg-yellow-400")} >{children}</button>; }
function Status({ on, label }) { return <span className={cx("text-[10px] px-2 py-1 rounded-full font-semibold", on ? "bg-green-500/10 text-green-400" : "bg-white/5 text-white/30")}>{label || (on ? "ON" : "OFF")}</span>; }

const DEFAULT_BRANDING = { siteName:"Hollywood Studio AI", tagline:"From idea to final cut", defaultLang:"pt", defaultTheme:"dark", whatsapp:"", supportEmail:"", heroVideo:"/assets/cinematic-demo.mp4", logoMode:"real" };
export default function AdminBranding(){ const [branding,setBranding]=useState(DEFAULT_BRANDING); const [msg,setMsg]=useState(null); const [saving,setSaving]=useState(false); const update=p=>setBranding(b=>({...b,...p}));
  useEffect(()=>{fetch('/api/admin/platform').then(r=>r.ok?r.json():null).then(d=>d?.branding&&setBranding(d.branding)).catch(()=>{});},[]);
  const save=async()=>{setSaving(true);const r=await fetch('/api/admin/platform',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({branding})});const d=await r.json().catch(()=>({}));setMsg(r.ok?'Branding salvo':(d.error||'Erro ao salvar'));setSaving(false)};
  return <div><div className="mb-6 flex items-end justify-between"><div><h1 className="text-2xl font-bold text-white mb-1">Branding & Experience</h1><p className="text-sm text-white/40">Defina nome, idioma, tema, suporte e assets principais.</p></div><Button onClick={save} disabled={saving}>{saving?'Salvando…':'Salvar branding'}</Button></div>{msg&&<div className="mb-4 text-xs text-yellow-400 bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-3">{msg}</div>}<div className="grid grid-cols-1 lg:grid-cols-2 gap-5"><Card><h2 className="text-sm font-semibold mb-4">Identidade</h2><div className="space-y-3"><div><Label>Nome do site</Label><Input value={branding.siteName||''} onChange={e=>update({siteName:e.target.value})}/></div><div><Label>Tagline</Label><Input value={branding.tagline||''} onChange={e=>update({tagline:e.target.value})}/></div><div className="grid grid-cols-2 gap-3"><div><Label>Idioma padrão</Label><Select value={branding.defaultLang||'pt'} onChange={e=>update({defaultLang:e.target.value})}><option value="pt">Português</option><option value="en">English</option></Select></div><div><Label>Tema padrão</Label><Select value={branding.defaultTheme||'dark'} onChange={e=>update({defaultTheme:e.target.value})}><option value="dark">Dark</option><option value="light">Light</option></Select></div></div><div><Label>Modo de logo</Label><Select value={branding.logoMode||'real'} onChange={e=>update({logoMode:e.target.value})}><option value="real">Logo real</option><option value="minimal">Minimal</option><option value="text">Texto</option></Select></div></div></Card><Card><h2 className="text-sm font-semibold mb-4">Suporte & Conteúdo</h2><div className="space-y-3"><div><Label>WhatsApp comercial</Label><Input placeholder="https://wa.me/55..." value={branding.whatsapp||''} onChange={e=>update({whatsapp:e.target.value})}/></div><div><Label>Email suporte</Label><Input placeholder="contato@hollywoodstudio.ai" value={branding.supportEmail||''} onChange={e=>update({supportEmail:e.target.value})}/></div><div><Label>Vídeo hero/demo</Label><Input value={branding.heroVideo||''} onChange={e=>update({heroVideo:e.target.value})}/></div><div className="border border-white/10 rounded-lg p-3 bg-black/30"><p className="text-xs text-white/40 mb-2">Logo atual</p><img src="/assets/logo-hero.png" className="max-h-28 object-contain rounded"/></div></div></Card></div></div> }
